# Generated by Django 5.1.4 on 2024-12-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('image', models.ImageField(upload_to='bannertop')),
                ('deal', models.CharField(default='', max_length=200)),
                ('sale', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('link', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
