# Generated by Django 5.1.4 on 2024-12-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_main_category_category_sub_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner_area',
            new_name='Slider',
        ),
    ]
