# Generated by Django 5.1.4 on 2024-12-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_slider_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('sale', models.CharField(choices=[('intelligent', 'intelligent'), ('onsale', 'onsale'), ('hotsale', 'hotsale')], default='', max_length=200)),
                ('images', models.ImageField(upload_to='bannerarea')),
                ('discount', models.IntegerField()),
            ],
        ),
    ]
