# Generated by Django 5.1.4 on 2025-01-03 12:34

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_maincategory_category_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner_area',
            name='sale',
            field=models.CharField(choices=[('intelligent', 'intelligent'), ('onsale', 'onsale'), ('hotsale', 'hotsale')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='banner_area',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='maincategory',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='deal',
            field=models.CharField(choices=[('New Deal', 'New Deal'), ('Hot Deal', 'Hot Deal'), ('New arrival', 'New arrival'), ('Best seller', 'Best seller')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('price', models.PositiveBigIntegerField(default=0, null=True)),
                ('discount', models.PositiveBigIntegerField(default=0, null=True)),
                ('featured_image', models.CharField(max_length=200, null=True)),
                ('total', models.PositiveBigIntegerField(default=0, null=True)),
                ('available', models.PositiveBigIntegerField(default=0, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('product_information', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.CharField(blank=True, max_length=555, null=True)),
                ('brand', models.CharField(max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.category')),
            ],
        ),
    ]
